config/routes.rb
Rails.application.routes.draw do
  get 'team/index'

  root 'races#index'

  get 'home', to: 'home#home', :path => ''

  resources :runners
  resources :races do
    member do
      get 'get_race_results', :path => "api/race_results/:id"
    end
  end

  get 'get_race_results', to: 'races#get_race_results', :path => "api/race_results/:id"
  get 'get_teams', to: 'races#get_teams', :path => "api/get_teams/:id"

  resources :teams
  get 'get_team_results', to: 'teams#get_team_results', :path => "api/team_results/:id"

  resources :projected_races, :path => 'predictions'

  get 'get_projected_race_results', to: 'projected_races#get_projected_race_results', :path => "api/projected_race_results/:id"
  get 'get_projected_teams', to: 'projected_races#get_projected_teams', :path => "api/get_projected_teams/:id"

  get 'search_races', to: 'search#search_races'
  get 'search_runners', to: 'search#search_runners'
  get 'search_all', to: 'search#search_all'

  get 'blog', to: 'blog#index', :path => 'blog'
  get 'club_points_2016', to: 'blog#club_points_2016', :path => "blog/club_points_2016"
  get 'readme', to: 'blog#readme', :path => "blog/readme"

end

app/models/race.rb
require 'elasticsearch/model'

class Race < ActiveRecord::Base
	include Elasticsearch::Model
 	include Elasticsearch::Model::Callbacks
 	extend FriendlyId
  friendly_id :generate_custom_slug, :use => :slugged

	has_many :results, inverse_of: :race, dependent: :destroy
	has_many :runners, through: :results

	settings index: {
		number_of_shards: 1
		},
		analysis: {
			filter: {
			    autocomplete_filter: {
			      type: "edge_ngram",
			      min_gram: 6,
			      max_gram: 7
		    	}
			},
			analyzer: {
		    autocomplete: {
		      tokenizer: "lowercase",
		      filter: ["lowercase", "autocomplete_filter"],
		      type: "custom"
		    }
		  }
	  }	do
	  mappings dynamic: 'true' do
	    indexes :name, analyzer: 'autocomplete'
	  end

	end

	def self.search(query)
	  __elasticsearch__.search(
	    {
	      query: {
	        multi_match: {
	          query: query,
	          fields: ['name']
	        }
	      },
	      fields: ['name', 'id', 'date', 'slug']
	    }
	  )
	end

	def generate_custom_slug
    "#{self.name} #{self.date.year}"
  end

  def set_team_results(team_champs = false)
    puts 'setting_team_results'
    categories = ["open", "40", "50", "60"]

    categories.each do |category|
      if category == "open"
        scoring_results = results
        if team_champs
          men_scoring_count = 10
          women_scoring_count = 10
          display_count = 12
        else
          men_scoring_count = 5
          women_scoring_count = 5
          display_count = 10
        end
      else
        scoring_results = results.includes(:runner).where("age >= ?", category)
        if team_champs
          if category == "40"
            men_scoring_count = 5
            display_count = 10
          else
            men_scoring_count = 3
            display_count = 6
          end
          women_scoring_count = 3
          display_count = 6
        else
          men_scoring_count = 3      
          women_scoring_count = 3
          display_count = 6
        end
      end

      team_rosters = {}

      scoring_results.select{|pr| pr.team != '---' && !pr.team.blank?}.each do |pr|
        next if pr.team.blank? || pr.team == "0"

        if !pr.net_time.blank?
          runner_time = pr.net_time
        elsif !pr.finish_time.blank?
          runner_time = pr.finish_time
        else
          runner_time = pr.gun_time
        end

        if runner_time =~ /^\d\d:\d\d$/
          runner_time = "0:" + runner_time
        end

        next if (runner_time =~ /^(\d+:)?\d+:\d+$/).nil?

        net_time_date = DateTime.parse(runner_time)
        net_time_in_seconds = net_time_date.hour * 60 * 60 + net_time_date.min * 60 + net_time_date.sec
        net_time = "#{sprintf "%02d",(net_time_in_seconds / 3600).floor}:#{sprintf "%02d", ((net_time_in_seconds % 3600) / 60).floor}:#{sprintf "%02d", ((net_time_in_seconds % 3600) % 60).round}"

        if team_rosters.include? pr.team
          if pr.sex == 'm'
            team_rosters[pr.team]['m'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          else
            team_rosters[pr.team]['f'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          end
        else
          team_rosters[pr.team] = {'m' => [], 'f' => []}
          if pr.sex == 'm'
            team_rosters[pr.team]['m'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          else
            team_rosters[pr.team]['f'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          end
        end
      end

      male_team_scores = []
      female_team_scores = []

      team_rosters.each do |team, runners|
        runners['m'].sort_by!{ |r| r["net_time_in_seconds"] }
        if runners['m'].count >= men_scoring_count
          total_time_in_seconds = runners['m'].take(men_scoring_count).inject(0) { |total_time, runner| total_time + runner["net_time_in_seconds"] }
          total_time = "#{sprintf "%02d",(total_time_in_seconds / 3600).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) / 60).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) % 60).round}"
          
          runners_hash = {}

          runners['m'].take(display_count).each_with_index do |value, index|
          	runners_hash[index.to_s] = value
          end

          male_team_scores << { team: team, total_time_in_seconds: total_time_in_seconds, total_time: total_time, runners: runners_hash }
        end
        runners['f'].sort_by!{ |r| r["net_time_in_seconds"] }
        if runners['f'].count >= women_scoring_count
          total_time_in_seconds = runners['f'].take(women_scoring_count).inject(0) { |total_time, runner| total_time + runner["net_time_in_seconds"] }
          total_time = "#{sprintf "%02d",(total_time_in_seconds / 3600).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) / 60).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) % 60).round}"
          
          runners_hash = {}

          runners['f'].take(display_count).each_with_index do |value, index|
          	runners_hash[index.to_s] = value
          end

          female_team_scores << { team: team, total_time_in_seconds: total_time_in_seconds, total_time: total_time, runners: runners_hash }
        end
      end

      male_team_scores.sort_by!{ |team| team[:total_time_in_seconds] }
      female_team_scores.sort_by!{ |team| team[:total_time_in_seconds] }

      case category
      when "40"
        self.men_40_results = male_team_scores
        self.women_40_results = female_team_scores
      when "50"
        self.men_50_results = male_team_scores
        self.women_50_results = female_team_scores
      when "60"
        self.men_60_results = male_team_scores
        self.women_60_results = female_team_scores
      when "open"
        self.men_results = male_team_scores
        self.women_results = female_team_scores
      end
    end
    self.save!
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    if params[:year]
      year = params[:year]
    else
      year = Time.now.year
    end

    @races = Race.where('extract(year from date) = ?', year).order(:date => :desc)

    respond_to do |format|
      format.html
      format.json { render :json => {:success => true, :html => (render_to_string "races/_race_list", :formats => [:html], :layout => false, :locals => { races: @races } ) } }
    end
  end

  # GET /races/1
  # GET /races/1.json
  def show
    @race_time_array = get_race_time_title_and_type(@race)

    @results = []
    if @race.men_results && @race.women_results
      @men_results = @race.men_results
      @women_results = @race.women_results

      if @men_results.count < 10
        @men_teams_to_display = @men_results.count
      else
        @men_teams_to_display = 10
      end
      if @women_results.count < 10
        @women_teams_to_display = @women_results.count
      else
        @women_teams_to_display = 10
      end

      @results << {:men => @men_results, :women => @women_results, :men_teams => @men_teams_to_display, :women_teams => @women_teams_to_display, :title => "Team Results", :score_count => 5}
    end

    if @race.men_40_results && @race.women_40_results

      @men_40_results = @race.men_40_results
      @women_40_results = @race.women_40_results

      if @men_results.count < 5
        @men_40_teams_to_display = @men_40_results.count
      else
        @men_40_teams_to_display = 5
      end
      if @women_40_results.count < 5
        @women_40_teams_to_display = @women_40_results.count
      else
        @women_40_teams_to_display = 5
      end

      @results << {:men => @men_40_results, :women => @women_40_results, :men_teams => @men_40_teams_to_display, :women_teams => @women_40_teams_to_display, :title => "Masters 40+ Team Results", :score_count => 3}
    end

    if @race.men_50_results && @race.women_50_results

      @men_50_results = @race.men_50_results
      @women_50_results = @race.women_50_results

      if @men_50_results.count < 5
        @men_50_teams_to_display = @men_50_results.count
      else
        @men_50_teams_to_display = 5
      end
      if @women_50_results.count < 5
        @women_50_teams_to_display = @women_50_results.count
      else
        @women_50_teams_to_display = 5
      end

      @results << {:men => @men_50_results, :women => @women_50_results, :men_teams => @men_50_teams_to_display, :women_teams => @women_50_teams_to_display, :title => "Masters 50+ Team Results", :score_count => 3}
    end

    if @race.men_60_results && @race.women_60_results
      @men_60_results = @race.men_60_results
      @women_60_results = @race.women_60_results

      if @men_60_results.count < 5
        @men_60_teams_to_display = @men_60_results.count
      else
        @men_60_teams_to_display = 5
      end
      if @women_60_results.count < 5
        @women_60_teams_to_display = @women_60_results.count
      else
        @women_60_teams_to_display = 5
      end

      @results <<{:men => @men_60_results, :women => @women_60_results, :men_teams => @men_60_teams_to_display, :women_teams => @women_60_teams_to_display, :title => "Masters 60+ Team Results", :score_count => 3}
    end
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_race_results
    draw = params[:draw]
    race_slug = params[:id]
    limit = params[:length]
    offset = params[:start]
    columns = params[:columns]
    asc_or_desc = params[:order]["0"][:dir]
    order_by_column = columns[params[:order]["0"][:column]][:data]
    searches = {
      "team" => "",
      "sex" => "",
      "full_name" => "",
      "age_range" => params[:age_range],
      "city" => ""
    }

    columns.each do |col|
      if !col[1][:search][:value].empty?
        searches[col[1][:data]] = col[1][:search][:value].strip.downcase
      end
    end

    sql_results = " SELECT results.*, runner.slug, runner.full_name"
    sql_filtered_count = " SELECT COUNT(results)"
    sql_search =
      "
        FROM results
        LEFT JOIN runners as runner
        ON results.runner_id = runner.id
        WHERE results.race_id = (
          SELECT id
          FROM races
          WHERE races.slug = '#{race_slug}'
        )
      "

    if !searches["city"].blank?
      sql_search += "AND results.city LIKE '%#{searches["city"]}%'"
    end

    if !searches["full_name"].blank?
      searches["full_name"].split(' ').each do |search_term|
        sql_search += "AND runner.first_name || runner.last_name LIKE '%#{search_term}%'"
      end
    end

    if !searches["team"].blank?
      sql_search += "AND results.team LIKE '#{searches["team"]}'"
    end

    if !searches["sex"].blank?
      sql_search += "AND results.sex LIKE '#{searches["sex"]}'"
    end

    if !searches["age_range"].blank?
      min_age = searches["age_range"][0..1]
      max_age = searches["age_range"][3..4]
      sql_search += "AND results.age BETWEEN #{min_age} AND #{max_age}"
    end

    sql_filtered_count += sql_search

    sql_search +=
    " 
      ORDER BY results.#{order_by_column} #{asc_or_desc}
        LIMIT #{limit}
        OFFSET #{offset};
    "

    sql_results += sql_search

    results = Result.find_by_sql(sql_results)
    filtered_results_count = ActiveRecord::Base.connection.execute(sql_filtered_count)[0]["count"]

    response = {
      draw: draw,
      recordsTotal: Race.find_by_slug(params[:id]).results.count,
      recordsFiltered: filtered_results_count,
      data: results.as_json
    }

    render json: response
  end

  def get_teams
    teams = Race.find_by_slug(params[:id]).results.pluck(:team).uniq.sort

    render json: teams.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
        @race = Race.friendly.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params[:race]
    end

    def get_race_time_title_and_type(race)
      if race.results.first.net_time
        ["Net Time", "net_time"]
      elsif race.results.first.finish_time
        ["Finish Time", "finish_time"]
      else
        ["Gun Time", "gun_time"]
      end
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_race_list.html.erb
<table class="index-page-table">
	<thead>
		<tr class="header-column">
			<th class="race-name">Race</th>
			<th class="race-distance">Distance</th>
			<th class="race-date">Date</th>
		</tr>
	</thead>
	<tbody class="race-table-body">
		<% races.each do |race| %>
	  	<tr class="index-page-link js-index-page-link" data-href="<%=race_url(race.slug)%>">
  			<td class="race-name">
  					<%=race.name%>
  			</td>
  			<td class='race-distance'><%=race.distance%>
	  			<% if race.distance == 1.0 %>
	      	  mile
	       	<% else %>
	          miles
	        <% end %>
	     	</td>
  			<td class='race-date'><%=race.date.strftime("%m/%d/%Y")%></td>
			</tr>
		<% end %>
	</tbody>
</table>

<script>
	$(".js-index-page-link").click(function() {
        window.document.location = $(this).data("href");
    });
</script>

app/views/races/_search_race.html.erb
<ul>
  <% races.each do |race| %>
    <li>
        <%= link_to "#{race[:name]} : #{race[:date]}", controller: "races", action: "show", id: "#{race[:id]}"%>
    </li>
  <% end %>
</ul>

app/views/races/index.html.erb
<div class="races-container">
	<div class="sub-title-container">
		race results  	
	</div>
	Select year:
	<select class="select-box js-year-select">
		<% (Time.now.year).downto(1986) do |year| %>
		  <option value=<%="#{year}"%>><%="#{year}"%></option>
	  <% end %>
	</select>
	<div class="races-list-container">
	</div>
</div>

<script>
$(document).ready(function(){

	var year = $( '.js-year-select' ).val();
	$.ajax({
		  url: "<%= races_url %>",
		  data: {"year": year},
		  dataType: 'json',
		  success: function(data) {
		  	$('.races-list-container').html(data.html);
		  }
		});

	$( '.js-year-select' ).change( function () {
		$('.races-list-container').html(spinner.el);
		var year = $( '.js-year-select' ).val();

	    $.ajax({
			  url: "<%= races_url %>",
			  data: {"year": year},
			  dataType: 'json',
			  success: function(data) {
			  	$('.races-list-container').html(data.html);
			  }
			});
   	});

	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-60193441-1', 'auto');
	ga('send', 'pageview');
});
</script>

app/views/races/show.html.erb
<%- model_class = Race -%>
<div class="results-page-header page-header">
  <h1><%= @race.name %></h1>
  <dl>
    <% @race.attributes.each do |attribute, value| %>
      <% next if value.nil? %>
      <% next if ["club_points", "id", "created_at", "updated_at", "date", "temperature", "humidity", "name", "slug", "men_results", "women_results", "men_40_results", "women_40_results", "men_50_results", "women_50_results", "men_60_results", "women_60_results"].include? attribute %>
      <dt class="race-attribute">
        <strong>
          <% if attribute == "date_and_time" %>
            date / time:
          <% else %>
            <%= attribute %>:
          <% end %>
        </strong>
      </dt>
      <dd class="race-attribute-value">
        <%= value %>
        <% case attribute %>
        <% when "distance" %>
          <% if value == 1.0 %>
            mile
          <% else %>
            miles
          <% end %>
        <% end %>
      </dd>
    <% end %>
  </dl>
</div>


<div class="race-page-content">
  <div class="race-results-table">
      <table class="results-table table table-hover" id="resultTable">
          <thead>
              <tr>
                  <th class="race-header-title">Overall</th>
                  <th class="race-header-title">Gender</th>
                  <th class="race-header-title">AG</th>
                  <th class="race-header-title">
                    <input type="text" placeholder="City" class="city-text-input"/>
                  </th>
                  <th class="race-header-title">
                    <input type="text" placeholder="Runner" class="runner-text-input"/>
                  </th>
                  <th>
                    <select class="race-header-select race-select-team">
                      <option value="" select="selected">
                        Team
                      </option>
                      <option value="nbr">
                        NBR
                      </option>
                    </select>
                  </th>
                  <th>
                    <select class="race-header-select race-select-sex">
                      <option value="" select="selected">
                        Sex
                      </option>
                      <option value="M">
                        M
                      </option>
                      <option value="F">
                        F
                      </option>
                    </select>
                  </th>
                  <th>
                    <select class="race-header-select race-select-age">
                      <option value="" select="selected">
                        Age
                      </option>
                      <option value="00-19">
                        &#60; 19
                      </option>
                      <% (2..9).each do |i| %>
                        <option value="<%=i%>0-<%=i%>4">
                          <%=i%>0 - <%=i%>4
                        </option>
                        <option value="<%=i%>5-<%=i%>9">
                          <%=i%>5 - <%=i%>9
                        </option>
                      <% end %>
                    </select>
                  </th>
                  <th class="race-header-title">Bib</th>
                  <th class="race-header-title"> <%= @race_time_array[0] %> </th>
                  <th class="race-header-title">Pace</th>
                  <th class="race-header-title">AG Time</th>
                  <th class="race-header-title">AG%</th>
              </tr>
          </thead>
          <tbody>
          </tbody>
      </table>
  </div>
</div>

<% @results.each do |result| %>
  <div class="team-results-main-container">
    <div class="team-results-title">
      <h2> <%= result[:title] %> </h2>
    </div>
    <div class="mens-results-container team-results-column">
      <h3 class="team-gender-results-title"> Men's Results </h3>
      <% result[:men_teams].times do |i| %>
        <% break if result[:men][i].nil? %>
        <div class="team-results-container">
          <div class="team-title-container group">
            <div class="team-title">
              <%= i + 1  %>
              :
              <% if !TEAMS[result[:men][i]["team"]].nil? %>
                <a href="<%=team_url(result[:men][i]["team"])%>"> <%= TEAMS[result[:men][i]["team"]] %> </a>
              <% else %>
                <%= result[:men][i]["team"].upcase %>
              <% end %>
            </div>
            <div class="team-time"><%= result[:men][i]["total_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %></div>
          </div>
          <div class="team-runners-container">
            <% JSON.parse(result[:men][i]["runners"].gsub('\"', '"').gsub('=>',':')).collect{|k,v| v}.each_with_index do |runner, team_spot| %>
              <div class="runner-container">
                <div class="runner-name-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                   <a href="<%=runner_url runner["slug"]%>"> <%= runner["name"] %></a>
                </div>
                <div class="runner-time-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                  <%= runner["net_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="womens-results-container team-results-column">
      <h3 class="team-gender-results-title"> Women's Results </h3>
      <% result[:women_teams].times do |i| %>
        <% break if result[:women][i].nil? %>
        <div class="team-results-container">
          <div class="team-title-container group">
            <div class="team-title">
              <%= i + 1  %>
              :
              <% if !TEAMS[result[:women][i]["team"]].nil? %>
                <a href="<%=team_url(result[:women][i]["team"])%>"> <%= TEAMS[result[:women][i]["team"]] %> </a>
              <% else %>
                <%= result[:women][i]["team"].upcase %>
              <% end %>
            </div>
            <div class="team-time"><%= result[:women][i]["total_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %></div>
          </div>
          <div class="team-runners-container">
            <% JSON.parse(result[:women][i]["runners"].gsub('\"', '"').gsub('=>',':')).collect{|k,v| v}.each_with_index do |runner, team_spot| %>
              <div class="runner-container">
                <div class="runner-name-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                  <a href="<%=runner_url runner["slug"]%>"> <%= runner["name"] %></a>
                </div>
                <div class="runner-time-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                  <%= runner["net_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<script>
$( document ).ready(function() {
  var allowFilter = ['resultTable'];

  var $resultsTable = $('.results-table').DataTable( {
      "dom": "ip<bottom'results-table-header'pi>",
      "processing": true,
      "serverSide": true,
      "ajax": {
        "url": "<%= get_race_results_url(@race.slug) %>",
        "data": function(d) {
          d.age_range = $( '.race-select-age' ).val()
        }
      },
      "columns": [
        { "data": "overall_place", "width": "70px", "orderable": true, "searchable": false},
        { "data": "gender_place", "width": "70px", "orderable": true, "searchable": false},
        { "data": "age_place", "width": "65px", "orderable": true, "searchable": false},
        { "data": "city", "orderable": false},
        { "data": "full_name", "orderable": false},
        { "data": "team", "orderable": false},
        { "data": "sex", "orderable": false},
        { "data": "age", "orderable": false, "searchable": false},
        { "data": "bib",  "orderable": true, "searchable": false },
        { "data": "net_time",  "orderable": true, "searchable": false },
        { "data": "pace_per_mile",  "orderable": true, "searchable": false },
        { "data": "ag_time",  "orderable": true, "searchable": false },
        { "data": "ag_percent",  "orderable": true, "searchable": false }
      ],
      "createdRow": function ( row, data, index ) {
        $('td:eq(4)', row)
        .addClass('result-table-clickable-td')
        .html('\
                  <a href="<%= root_url %>' + 'runners/' + data.slug + '">\
                    <div class="result-table-clickable-field"> \
                      ' + data.full_name + ' \
                    </div> \
                  </a> '
                );

        if (data.team != null && data.team != 0 && data.team.replace(/\s/g, "").length != 0) {
          var teamColHTML = '<a href="<%= root_url %>' + 'teams/' + data.team + '"> \
              <div class="result-table-clickable-field results-table-team"> \
                ' + data.team + '\
              </div> \
            </a> \
          ';
        } else {
          var teamColHTML = data.team;
        }

        $('td:eq(5)', row)
          .addClass('result-table-clickable-td')
          .html(teamColHTML);

        if (data.net_time != null) {
          var time = data.net_time
        } else if (data.finish_time != null) {
          var time = data.finish_time
        } else {
          var time = data.gun_time
        } 
        $('td:eq(9)', row)
          .html(time);


        return row;
      }
    });
  
    // get team selection
    $.get("<%= get_teams_url(@race.slug) %>", function(data) {
      $(data).each(function(index, team) {
        $('.race-select-team').append( '<option value="'+team+'">'+team+'</option>' );
      })
    })

    // City Search
    $( '.city-text-input' ).on( 'keyup change', function () {
        $resultsTable
            .column( 3 )
            .search( this.value )
            .draw();
    } );

    // Text Search
    $( '.runner-text-input' ).on( 'keyup change', function () {
        $resultsTable
            .column( 4 )
            .search( this.value )
            .draw();
    } );

    // Team Select
    $( '.race-select-team' ).change( function () {
        $resultsTable
            .column( 5 )
            .search( this.value )
            .draw();
    } );

    // Gender Select
    $( '.race-select-sex' ).change( function () {
        $resultsTable
            .column( 6 )
            .search( this.value, true, false )
            .draw();
    } );

    // Age group select
    $( '.race-select-age' ).change( function () {
        $resultsTable.draw();
    } );

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60193441-1', 'auto');
  ga('send', 'pageview');
});
</script>