config/routes.rb
Rails.application.routes.draw do
  get 'team/index'

  root 'races#index'

  get 'home', to: 'home#home', :path => ''

  resources :runners
  resources :races do
    member do
      get 'get_race_results', :path => "api/race_results/:id"
    end
  end

  get 'get_race_results', to: 'races#get_race_results', :path => "api/race_results/:id"
  get 'get_teams', to: 'races#get_teams', :path => "api/get_teams/:id"

  resources :teams
  get 'get_team_results', to: 'teams#get_team_results', :path => "api/team_results/:id"

  resources :projected_races, :path => 'predictions'

  get 'get_projected_race_results', to: 'projected_races#get_projected_race_results', :path => "api/projected_race_results/:id"
  get 'get_projected_teams', to: 'projected_races#get_projected_teams', :path => "api/get_projected_teams/:id"

  get 'search_races', to: 'search#search_races'
  get 'search_runners', to: 'search#search_runners'
  get 'search_all', to: 'search#search_all'

  get 'blog', to: 'blog#index', :path => 'blog'
  get 'club_points_2016', to: 'blog#club_points_2016', :path => "blog/club_points_2016"
  get 'readme', to: 'blog#readme', :path => "blog/readme"

end

app/models/projected_race.rb
class ProjectedRace < ActiveRecord::Base
  extend FriendlyId
   friendly_id :generate_custom_slug, :use => :slugged

   has_many :projected_results, inverse_of: :race, dependent: :destroy
   has_many :runners, through: :projected_results

   def generate_custom_slug
     self.name
   end

   def set_team_results(team_champs = false)
    puts 'assigning place values'

    projected_results.order(:net_time).each_with_index do |pr, i|
      pr.overall_place = i + 1
      if i % 100 == 0
        puts "on overall results #{i}"
      end
      pr.save!
    end;nil
    puts "overall places set"
    projected_results.where(sex: 'M').order(:net_time).each_with_index do |pr, i|
      pr.gender_place = i + 1
      if i % 100 == 0
        puts "on male results #{i}"
      end
      pr.save!
    end;nil
    puts "male places set"
    projected_results.where(sex: 'F').order(:net_time).each_with_index do |pr, i|
      pr.gender_place = i + 1
      if i % 100 == 0
        puts "on female results #{i}"
      end
      pr.save!
    end;nil
    puts "female places set"

    puts 'setting_team_results'
    categories = ["open", "40", "50", "60"]

    categories.each do |category|
      puts "category is #{category}"

      if category == "open"
        scoring_results = projected_results
        if team_champs
          men_scoring_count = 10
          women_scoring_count = 10
          display_count = 12
        else
          men_scoring_count = 5
          women_scoring_count = 5
          display_count = 10
        end
      else
        scoring_results = projected_results.includes(:runner).where("age >= ?", category)
        if team_champs
          if category == "40"
            men_scoring_count = 5
            display_count = 10
          else
            men_scoring_count = 3
            display_count = 6
          end
          women_scoring_count = 3
          display_count = 6
        else
          men_scoring_count = 3      
          women_scoring_count = 3
          display_count = 6
        end
      end

      team_rosters = {}

      scoring_results.select{|pr| pr.team != '---' && !pr.team.blank?}.each do |pr|
        next if pr.net_time.blank? || pr.team.blank? || pr.team == "0"
        runner_time = pr.net_time
        begin
          net_time_date = DateTime.parse(runner_time)
        rescue => e
          puts "error parsing net time for #{pr.inspect} #{e}"
          next
        end
        net_time_in_seconds = net_time_date.hour * 60 * 60 + net_time_date.min * 60 + net_time_date.sec
        net_time = "#{sprintf "%02d",(net_time_in_seconds / 3600).floor}:#{sprintf "%02d", ((net_time_in_seconds % 3600) / 60).floor}:#{sprintf "%02d", ((net_time_in_seconds % 3600) % 60).round}"

        if team_rosters.include? pr.team
          if pr.sex == 'M'
            team_rosters[pr.team]['m'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          else
            team_rosters[pr.team]['f'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          end
        else
          team_rosters[pr.team] = {'m' => [], 'f' => []}
          if pr.sex == 'M'
            team_rosters[pr.team]['m'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug}
          else
            team_rosters[pr.team]['f'] << {"name" => pr.full_name, "net_time_in_seconds" => net_time_in_seconds, "net_time" => net_time, "slug" => pr.runner.slug }
          end
        end
      end

      male_team_scores = []
      female_team_scores = []

      team_rosters.each do |team, runners|
        runners['m'].sort_by!{ |r| r["net_time_in_seconds"] }
        if runners['m'].count >= men_scoring_count
          total_time_in_seconds = runners['m'].take(men_scoring_count).inject(0) { |total_time, runner| total_time + runner["net_time_in_seconds"] }
          total_time = "#{sprintf "%02d",(total_time_in_seconds / 3600).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) / 60).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) % 60).round}"
          
          runners_hash = {}

          runners['m'].take(display_count).each_with_index do |value, index|
          	runners_hash[index.to_s] = value
          end

          male_team_scores << { team: team, total_time_in_seconds: total_time_in_seconds, total_time: total_time, runners: runners_hash }
        end
        runners['f'].sort_by!{ |r| r["net_time_in_seconds"] }
        if runners['f'].count >= women_scoring_count
          total_time_in_seconds = runners['f'].take(women_scoring_count).inject(0) { |total_time, runner| total_time + runner["net_time_in_seconds"] }
          total_time = "#{sprintf "%02d",(total_time_in_seconds / 3600).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) / 60).floor}:#{sprintf "%02d", ((total_time_in_seconds % 3600) % 60).round}"
          
          runners_hash = {}

          runners['f'].take(display_count).each_with_index do |value, index|
          	runners_hash[index.to_s] = value
          end

          female_team_scores << { team: team, total_time_in_seconds: total_time_in_seconds, total_time: total_time, runners: runners_hash }
        end
      end

      male_team_scores.sort_by!{ |team| team[:total_time_in_seconds] }
      female_team_scores.sort_by!{ |team| team[:total_time_in_seconds] }

      case category
      when "40"
        self.men_40_results = male_team_scores
        self.women_40_results = female_team_scores
      when "50"
        self.men_50_results = male_team_scores
        self.women_50_results = female_team_scores
      when "60"
        self.men_60_results = male_team_scores
        self.women_60_results = female_team_scores
      when "open"
        self.men_results = male_team_scores
        self.women_results = female_team_scores
      end
    end
    self.save!
  end
end

app/controllers/projected_races_controller.rb
class ProjectedRacesController < ApplicationController
  before_action :set_projected_race, only: [:show, :edit, :update, :destroy]

  # GET /projected_races
  # GET /projected_races.json
  def index
    @projected_races = ProjectedRace.all.order(:date => :desc)
  end

  # GET /projected_races/1
  # GET /projected_races/1.json
  def show
    @results = []
    if @projected_race.men_results && @projected_race.women_results
      @men_results = @projected_race.men_results
      @women_results = @projected_race.women_results

      if @men_results.count < 10
        @men_teams_to_display = @men_results.count
      else
        @men_teams_to_display = 10
      end
      if @women_results.count < 10
        @women_teams_to_display = @women_results.count
      else
        @women_teams_to_display = 10
      end

      @results << {:men => @men_results, :women => @women_results, :men_teams => @men_teams_to_display, :women_teams => @women_teams_to_display, :title => "Team Results", :score_count => 5}
    end

    if @projected_race.men_40_results && @projected_race.women_40_results

      @men_40_results = @projected_race.men_40_results
      @women_40_results = @projected_race.women_40_results

      if @men_results.count < 10
        @men_40_teams_to_display = @men_40_results.count
      else
        @men_40_teams_to_display = 10
      end
      if @women_40_results.count < 10
        @women_40_teams_to_display = @women_40_results.count
      else
        @women_40_teams_to_display = 10
      end

      @results << {:men => @men_40_results, :women => @women_40_results, :men_teams => @men_40_teams_to_display, :women_teams => @women_40_teams_to_display, :title => "Masters 40+ Team Results", :score_count => 3}
    end

    if @projected_race.men_50_results && @projected_race.women_50_results

      @men_50_results = @projected_race.men_50_results
      @women_50_results = @projected_race.women_50_results

      if @men_50_results.count < 10
        @men_50_teams_to_display = @men_50_results.count
      else
        @men_50_teams_to_display = 10
      end
      if @women_50_results.count < 10
        @women_50_teams_to_display = @women_50_results.count
      else
        @women_50_teams_to_display = 10
      end

      @results << {:men => @men_50_results, :women => @women_50_results, :men_teams => @men_50_teams_to_display, :women_teams => @women_50_teams_to_display, :title => "Masters 50+ Team Results", :score_count => 3}
    end

    if @projected_race.men_60_results && @projected_race.women_60_results
      @men_60_results = @projected_race.men_60_results
      @women_60_results = @projected_race.women_60_results

      if @men_60_results.count < 10
        @men_60_teams_to_display = @men_60_results.count
      else
        @men_60_teams_to_display = 10
      end
      if @women_60_results.count < 10
        @women_60_teams_to_display = @women_60_results.count
      else
        @women_60_teams_to_display = 10
      end

      @results <<{:men => @men_60_results, :women => @women_60_results, :men_teams => @men_60_teams_to_display, :women_teams => @women_60_teams_to_display, :title => "Masters 60+ Team Results", :score_count => 3}
    end
  end

  def get_projected_race_results
    draw = params[:draw]
    race_slug = params[:id]
    limit = params[:length]
    offset = params[:start]
    columns = params[:columns]
    asc_or_desc = params[:order]["0"][:dir]
    order_by_column = columns[params[:order]["0"][:column]][:data]
    searches = {
      "team" => "",
      "sex" => "",
      "full_name" => "",
      "age_range" => params[:age_range]
    }

    columns.each do |col|
      if !col[1][:search][:value].empty?
        searches[col[1][:data]] = col[1][:search][:value].strip.downcase
      end
    end

    sql_results = " SELECT results.*, runner.slug, runner.full_name"
    sql_filtered_count = " SELECT COUNT(results)"
    sql_search =
      "
        FROM projected_results as results
        LEFT JOIN runners as runner
        ON results.runner_id = runner.id
        WHERE results.projected_race_id = (
          SELECT id
          FROM projected_races
          WHERE projected_races.slug = '#{race_slug}'
        )
      "
    if !searches["full_name"].blank?
      searches["full_name"].split(' ').each do |search_term|
        sql_search += "AND runner.first_name || runner.last_name LIKE '%#{search_term}%'"
      end
    end

    if !searches["team"].blank?
      sql_search += "AND results.team LIKE '#{searches["team"]}'"
    end

    if !searches["sex"].blank?
      sql_search += "AND results.sex LIKE '#{searches["sex"].upcase}'"
    end

    if !searches["age_range"].blank?
      min_age = searches["age_range"][0..1]
      max_age = searches["age_range"][3..4]
      sql_search += "AND results.age BETWEEN #{min_age} AND #{max_age}"
    end

    sql_filtered_count += sql_search

    sql_search +=
    " 
      ORDER BY results.#{order_by_column} #{asc_or_desc}
        LIMIT #{limit}
        OFFSET #{offset};
    "

    sql_results += sql_search

    projected_results = Result.find_by_sql(sql_results)

    filtered_results_count = ActiveRecord::Base.connection.execute(sql_filtered_count)[0]["count"]

    response = {
      draw: draw,
      recordsTotal: ProjectedRace.find_by_slug(params[:id]).projected_results.count,
      recordsFiltered: filtered_results_count,
      data: projected_results.as_json
    }

    render json: response
  end

  def get_projected_teams
    teams = ProjectedRace.find_by_slug(params[:id]).projected_results.pluck(:team).uniq.sort

    render json: teams.as_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projected_race
        @projected_race = ProjectedRace.friendly.find_by_slug!(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projected_race_params
      params[:projected_race]
    end
end

app/helpers/projected_races_helper.rb
module ProjectedRacesHelper
end

app/views/projected_races/index.html.erb
<div class="races-container">
	<div class="sub-title-container projected-races-container">
		race predictions
	</div>
	<% if @projected_races.empty? %>
		There aren't any race predictions right now.
	<% else %>
		<table class="index-page-table">
			<thead>
				<tr class="header-column">
					<th class="race-name">Race</th>
					<th class="race-distance">Distance</th>
					<th class="race-date">Date</th>
				</tr>
			</thead>
			<tbody class="race-table-body">
				<% @projected_races.each do |projected_race| %>
			  	<tr class="index-page-link js-index-page-link" data-href="<%=projected_race_url(projected_race.slug)%>">
		  			<td class="race-name">
		  					<%=projected_race.name%>
		  			</td>
		  			<td class='race-distance'><%=projected_race.distance%>
			  			<% if projected_race.distance == 1.0 %>
			      	  mile
			       	<% else %>
			          miles
			        <% end %>
			     	</td>
		  			<td class='race-date'><%=projected_race.date.strftime("%m/%d/%Y")%></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
</div>

<script>
$(document).ready(function(){
	$(".js-index-page-link").click(function() {
	    window.document.location = $(this).data("href");
	});

	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-60193441-1', 'auto');
	ga('send', 'pageview');
});
</script>

app/views/projected_races/show.html.erb
<%- model_class = ProjectedRace -%>
<div class="results-page-header page-header">
  <h1>Prediction: <%= @projected_race.name %></h1>

  <dl>
    <% @projected_race.attributes.each do |attribute, value| %>
      <% next if value.nil? %>
      <% next if ["club_points", "id", "created_at", "updated_at", "date", "temperature", "humidity", "name", "slug", "men_results", "women_results", "men_40_results", "women_40_results", "men_50_results", "women_50_results", "men_60_results", "women_60_results"].include? attribute %>
      <dt class="race-attribute">
        <strong>
          <% if attribute == "date_and_time" %>
            date / time:
          <% else %>
            <%= attribute %>:
          <% end %>
        </strong>
      </dt>
      <dd class="race-attribute-value">
        <%= value %>
        <% case attribute %>
        <% when "distance" %>
          <% if value == 1.0 %>
            mile
          <% else %>
            miles
          <% end %>
        <% end %>
      </dd>
    <% end %>
  </dl>
</div>


<div class="race-page-content">
  <div class="race-results-table">
      <table class="results-table table table-hover" id="resultTable">
          <thead>
              <tr>
                  <th class="race-header-title">Overall</th>
                  <th class="race-header-title">Gender</th>
                  <th class="race-header-title">
                    <input type="text" placeholder="Runner" class="runner-text-input"/>
                  </th>
                  <th>
                    <select class="race-header-select race-select-team">
                      <option value="" select="selected">
                        Team
                      </option>
                      <option value="nbr">
                        NBR
                      </option>
                    </select>
                  </th>
                  <th>
                    <select class="race-header-select race-select-sex">
                      <option value="" select="selected">
                        Sex
                      </option>
                      <option value="M">
                        M
                      </option>
                      <option value="F">
                        F
                      </option>
                    </select>
                  </th>
                  <th>
                    <select class="race-header-select race-select-age">
                      <option value="" select="selected">
                        Age
                      </option>
                      <option value="00-19">
                        &#60; 19
                      </option>
                      <% (2..9).each do |i| %>
                        <option value="<%=i%>0-<%=i%>4">
                          <%=i%>0 - <%=i%>4
                        </option>
                        <option value="<%=i%>5-<%=i%>9">
                          <%=i%>5 - <%=i%>9
                        </option>
                      <% end %>
                    </select>
                  </th>
                  <!-- <th class="race-header-title">Bib</th> -->
                  <th class="race-header-title">Net Time</th>
                  <th class="race-header-title">Pace</th>
                  <th class="race-header-title">AG%</th>
              </tr>
          </thead>
          <tbody>
          </tbody>
      </table>
  </div>
</div>

<% @results.each do |result| %>
  <div class="team-results-main-container">
    <div class="team-results-title">
      <h2> <%= result[:title] %> </h2>
    </div>
    <div class="mens-results-container team-results-column">
      <h3 class="team-gender-results-title"> Men's Results </h3>
      <% result[:men_teams].times do |i| %>
        <% break if result[:men][i].nil? %>
        <div class="team-results-container">
          <div class="team-title-container group">
            <div class="team-title">
              <%= i + 1  %>
              :
              <% if !TEAMS[result[:men][i]["team"]].nil? %>
                <a href="<%=team_url(result[:men][i]["team"])%>"> <%= TEAMS[result[:men][i]["team"]] %> </a>
              <% else %>
                <%= result[:men][i]["team"].upcase %>
              <% end %>
            </div>
            <div class="team-time"><%= result[:men][i]["total_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %></div>
          </div>
          <div class="team-runners-container">
            <% JSON.parse(result[:men][i]["runners"].gsub('\"', '"').gsub('=>',':')).collect{|k,v| v}.each_with_index do |runner, team_spot| %>
              <div class="runner-container">
                <div class="runner-name-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                   <a href="<%=runner_url runner["slug"]%>"> <%= runner["name"] %></a>
                </div>
                <div class="runner-time-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                  <%= runner["net_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="womens-results-container team-results-column">
      <h3 class="team-gender-results-title"> Women's Results </h3>
      <% result[:women_teams].times do |i| %>
      <% break if result[:women][i].nil? %>
        <div class="team-results-container">
          <div class="team-title-container group">
            <div class="team-title">
              <%= i + 1  %>
              :
              <% if !TEAMS[result[:women][i]["team"]].nil? %>
                <a href="<%=team_url(result[:women][i]["team"])%>"> <%= TEAMS[result[:women][i]["team"]] %> </a>
              <% else %>
                <%= result[:women][i]["team"].upcase %>
              <% end %>
            </div>
            <div class="team-time"><%= result[:women][i]["total_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %></div>
          </div>
          <div class="team-runners-container">
            <% JSON.parse(result[:women][i]["runners"].gsub('\"', '"').gsub('=>',':')).collect{|k,v| v}.each_with_index do |runner, team_spot| %>
              <div class="runner-container">
                <div class="runner-name-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                   <a href="<%=runner_url runner["slug"]%>"> <%= runner["name"] %></a>
                </div>
                <div class="runner-time-container <%= 'non-scoring-runner' if team_spot > result[:score_count] - 1 %>">
                  <%= runner["net_time"].prepend(' ').sub!(/\s0{1,2}:*0*|\s/, "") %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<script>
$( document ).ready(function() {
  var allowFilter = ['resultTable'];

  var $resultsTable = $('.results-table').DataTable( {
      "dom": "ip<bottom'results-table-header'pi>",
      "processing": true,
      "serverSide": true,
      "ajax": {
        "url": "<%= get_projected_race_results_url(@projected_race.slug) %>",
        "data": function(d) {
          d.age_range = $( '.race-select-age' ).val()
        }
      },
      "columns": [
        { "data": "overall_place", "width": "70px", "orderable": true, "searchable": false},
        { "data": "gender_place", "width": "70px", "orderable": true, "searchable": false},
        { "data": "full_name", "orderable": false},
        { "data": "team", "orderable": false},
        { "data": "sex", "orderable": false},
        { "data": "age", "orderable": false, "searchable": false},
        // { "data": "bib",  "orderable": true, "searchable": false },
        { "data": "net_time",  "orderable": true, "searchable": false },
        { "data": "pace_per_mile",  "orderable": true, "searchable": false },
        { "data": "ag_percent",  "orderable": true, "searchable": false }
      ],
      "createdRow": function ( row, data, index ) {
        $('td:eq(2)', row)
        .addClass('result-table-clickable-td')
        .html('\
                  <a href="<%= root_url %>' + 'runners/' + data.slug + '">\
                    <div class="result-table-clickable-field"> \
                      ' + data.full_name + ' \
                    </div> \
                  </a> '
                );

        if (data.team != null && data.team != 0 && data.team.replace(/\s/g, "").length != 0) {
          var teamColHTML = '<a href="<%= root_url %>' + 'teams/' + data.team + '"> \
              <div class="result-table-clickable-field results-table-team"> \
                ' + data.team + '\
              </div> \
            </a> \
          ';
        } else {
          var teamColHTML = data.team;
        }

        $('td:eq(3)', row)
          .addClass('result-table-clickable-td')
          .html(teamColHTML);

        return row;
      }
    });

    // get team selection
    $.get("<%= get_projected_teams_url(@projected_race.slug) %>", function(data) {
      $(data).each(function(index, team) {
        $('.race-select-team').append( '<option value="'+team+'">'+team+'</option>' );
      })
    })

    // Text Search
    $( '.runner-text-input' ).on( 'keyup change', function () {
        $resultsTable
            .column( 2 )
            .search( this.value )
            .draw();
    } );

    // Team Select
    $( '.race-select-team' ).change( function () {
        $resultsTable
            .column( 3 )
            .search( this.value )
            .draw();
    } );

    // Gender Select
    $( '.race-select-sex' ).change( function () {
        $resultsTable
            .column( 4 )
            .search( this.value )
            .draw();
    } );

    // Age group select
    $( '.race-select-age' ).change( function () {
        $resultsTable.draw();
    } );

    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-60193441-1', 'auto');
    ga('send', 'pageview');
});
</script>