config/routes.rb
Rails.application.routes.draw do
  get 'team/index'

  root 'races#index'

  get 'home', to: 'home#home', :path => ''

  resources :runners
  resources :races do
    member do
      get 'get_race_results', :path => "api/race_results/:id"
    end
  end

  get 'get_race_results', to: 'races#get_race_results', :path => "api/race_results/:id"
  get 'get_teams', to: 'races#get_teams', :path => "api/get_teams/:id"

  resources :teams
  get 'get_team_results', to: 'teams#get_team_results', :path => "api/team_results/:id"

  resources :projected_races, :path => 'predictions'

  get 'get_projected_race_results', to: 'projected_races#get_projected_race_results', :path => "api/projected_race_results/:id"
  get 'get_projected_teams', to: 'projected_races#get_projected_teams', :path => "api/get_projected_teams/:id"

  get 'search_races', to: 'search#search_races'
  get 'search_runners', to: 'search#search_runners'
  get 'search_all', to: 'search#search_all'

  get 'blog', to: 'blog#index', :path => 'blog'
  get 'club_points_2016', to: 'blog#club_points_2016', :path => "blog/club_points_2016"
  get 'readme', to: 'blog#readme', :path => "blog/readme"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="/icon.ico" rel="shortcut icon" />

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Running Statistics and Analysis </title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <script src="https://d3js.org/d3.v4.js"></script>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar">
      <div class="navbar-inner">
        <!-- <div class="container"> -->
        <!-- <a href="<%= home_url %>" class="header-logo"> -->
          <div class="logo-picture">
            <img src="<%=asset_path "runlogo.png"%>">
          </div>
          <div class="brand header-item"><div style="color:black">RUN</div><div style="color:white">GRAPHS</div></div>
        <!-- </a> -->
        <div class="header-search-bar">
          <form class="search-form">
            <input
              type="text"
              name="q"
              placeholder="Search for races and runners"
              id="all-search-input"
              class="header-search-bar-input"
              autocomplete="off">
          </form>
          <div class="all-results-container">
          </div>
        </div>
        <div class="header-buttons-container">
          <ul class="nav nav-pills">
            <li class='header-item' role="presentation"><a href="<%= races_url %>">RACE RESULTS</a></li>
            <li class='header-item' role="presentation"><a href="<%= projected_races_url %>">RACE PREDICTIONS </a></li>
            <li class='header-item' role="presentation"><a href="<%= teams_url %>">TEAM RECORDS</a></li>
            <!-- <li class='header-item' role="presentation"><a href="<%= blog_url %>">BLOG</a></li> -->
          </ul>
        <!-- </div> -->
        </div>
      </div>
    </div>
    <div class="container content-container">
      <div class="row">
        <div class="span12">
          <%= bootstrap_flash %>

          <%= yield %>
        </div>
      </div>
    </div>

    <footer>

    </footer>
   <!-- container -->

  <script type="text/javascript">
      $("#all-search-input").on("keyup", function (event) {
        var $currentTarget = $(event.currentTarget);
        $q = $("#all-search-input").val();

        if ($q.length >= 2) {

          $.ajax({
            url: "<%= search_all_url %>",
            type: "GET",
            data: {'q': $q},
            success: function (resp) {
              if (resp != '<ul>\n</ul>') {
                $('.all-results-container').html(resp);
                $('.all-results-container').show();
              } else {
                  $('.all-results-container').empty();
                  $('.all-results-container').hide();
                }
              }
          });
        } else {
          $('.all-results-container').hide();
        }
      });

      $(".search-form").on('submit', function(event) {
        event.preventDefault();
        $('.search-all-item').first().click();
        $('.all-results-container').hide();
        $(".search-form").find("input[type=text], textarea").val("");
      })

      // autofocus on text input when '/' is clicked if not in an input field
      $( 'body' ).keypress(function( event ) {
        if (!$("input").is(":focus")) {
          if ( event.which == 47 ) {
          event.preventDefault();
            $( ".search-form :input" ).focus();
          };
        }
      });

    	var spinner = new Spinner().spin();
    	$( 'a' ).click(function() {
    		$('.content-container').html(spinner.el);
    	})

  </script>
  </body>
</html>